name: Ejemplo CI/CD

on:
  push:

jobs: 
  inicio:
    runs-on: windows-latest
    steps:
      - name: mostrar texto
        run: echo "Hola mundo"

  build:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: mostrar texto
        run: echo "Clonar repositorio a guthub actions"
      - name: Clonar Repositorio
        uses: actions/checkout@v4.2.2
      - name: php
        run: |
          choco install php --version=8.1
          choco install composer
          php -v
          composer --version
      - name: Instalar MySql
        run: |
          choco install mysql --version=8.0.27
          Start-Service mysql
          mysql -u root -e "ALTER USER 'root'@'localhost'IDENTIFIED WITH mysql_native_password BY 'root';" mysql -u root -proot -e "CREATE DATABASEÂ lumen_db;"

  test:
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: texto
        run: echo "test"

  deploy:
    runs-on: windows-latest
    needs: [test]
    steps:
      - name: texto
        run: echo "deploy correctamente"
                